version: "3"
services:
  postgres:
    image: postgres:alpine
    # network_mode: host
    restart: always
    environment:
      - DATABASE_SSL_MODE=disable # only ment for local deploy
      - POSTGRES_PASSWORD=root
    expose:
      - 5432
    ports:
      - 5432:5432
