version: "3.7"

services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
  db:
    image: "postgres"
    ports:
      - 5432:5432
    volumes:
      - exampledb:/var/lib/postgresql/data
volumes:
  redis-data:
