fastlane_version '2.53.1'

before_all do
  ensure_git_branch
  ensure_git_status_clean
  git_pull
end

platform :ios do
   # iOS Lanes
end

platform :android do
    desc 'Build the Android application.'
    private_lane :build do
      gradle(task: 'clean', project_dir: 'android/')
      gradle(task: 'assemble', build_type: 'Release', project_dir: 'android/')
    end

  desc 'Ship to Playstore Beta.'
  lane :beta do
    build
    supply(track: 'beta', track_promote_to: 'beta')
    git_commit(path: ['./android/gradle.properties'], message: 'Bump versionCode')
    push_to_git_remote
  end
end