// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql_models

type InfectedEncounterCreateInput struct {
	StartOfCreatorHash   *string `json:"startOfCreatorHash"`
	PossibleInfectedHash *string `json:"possibleInfectedHash"`
	Rssi                 *int    `json:"rssi"`
	Hits                 *int    `json:"hits"`
	Time                 *int    `json:"time"`
}

type InfectedEncountersCreateInput struct {
	InfectedEncounters []*InfectedEncounterCreateInput `json:"infectedEncounters"`
}

type InfectedEncountersPayload struct {
	Ok bool `json:"ok"`
}

type InfectionSummary struct {
	HighRiskInteractions   *int `json:"HighRiskInteractions"`
	MiddleRiskInteractions *int `json:"MiddleRiskInteractions"`
	LowRiskInteractions    *int `json:"LowRiskInteractions"`
}
