// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package helpers

func alreadyConverted(roots []interface{}, check interface{}) bool {
	var matched int
	for _, root := range roots {
		if root == check {
			matched++
		}
	}
	return matched > 2
}
