// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package helpers

import (
	"github.com/web-ridge/contact-tracing/backend/graphql_models"
	"github.com/web-ridge/contact-tracing/backend/models"
)

func InfectionCreateKeysToGraphQL(am []*models.InfectionCreateKey) []*graphql_models.InfectionCreateKey {
	ar := make([]*graphql_models.InfectionCreateKey, len(am))
	for i, m := range am {
		ar[i] = InfectionCreateKeyToGraphQL(m)
	}
	return ar
}

func InfectionCreateKeyToGraphQL(m *models.InfectionCreateKey) *graphql_models.InfectionCreateKey {
	if m == nil {
		return nil
	}

	r := &graphql_models.InfectionCreateKey{
		Key:      m.Key,
		Password: m.Password,
	}

	return r
}
