// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package helpers

import (
	"github.com/volatiletech/sqlboiler/boil"
	"github.com/web-ridge/contact-tracing/backend/graphql_models"
	"github.com/web-ridge/contact-tracing/backend/models"
)

func DeviceKeyCreateInputsToBoiler(am []*graphql_models.DeviceKeyCreateInput) []*models.DeviceKey {
	ar := make([]*models.DeviceKey, len(am))
	for i, m := range am {
		ar[i] = DeviceKeyCreateInputToBoiler(
			m,
		)
	}
	return ar
}

func DeviceKeyCreateInputToBoiler(
	m *graphql_models.DeviceKeyCreateInput,
) *models.DeviceKey {
	if m == nil {
		return nil
	}
	r := &models.DeviceKey{
		Hash:     m.Hash,
		Password: m.Password,
		Time:     m.Time,
	}
	return r
}

func DeviceKeyCreateInputToModelM(
	input map[string]interface{},
	m graphql_models.DeviceKeyCreateInput,
) models.M {
	modelM := models.M{}
	for key, _ := range input {
		switch key {
		case "hash":
			modelM[models.DeviceKeyColumns.Hash] = m.Hash
		case "password":
			modelM[models.DeviceKeyColumns.Password] = m.Password
		case "time":
			modelM[models.DeviceKeyColumns.Time] = m.Time
		}
	}
	return modelM
}

func DeviceKeyCreateInputToBoilerWhitelist(input map[string]interface{}, extraColumns ...string) boil.Columns {
	columnsWhichAreSet := []string{}
	for key, _ := range input {
		switch key {
		case "hash":
			columnsWhichAreSet = append(columnsWhichAreSet, models.DeviceKeyColumns.Hash)
		case "password":
			columnsWhichAreSet = append(columnsWhichAreSet, models.DeviceKeyColumns.Password)
		case "time":
			columnsWhichAreSet = append(columnsWhichAreSet, models.DeviceKeyColumns.Time)
		}
	}
	columnsWhichAreSet = append(columnsWhichAreSet, extraColumns...)
	return boil.Whitelist(columnsWhichAreSet...)
}

func InfectedEncounterCreateInputsToBoiler(am []*graphql_models.InfectedEncounterCreateInput) []*models.InfectedEncounter {
	ar := make([]*models.InfectedEncounter, len(am))
	for i, m := range am {
		ar[i] = InfectedEncounterCreateInputToBoiler(
			m,
		)
	}
	return ar
}

func InfectedEncounterCreateInputToBoiler(
	m *graphql_models.InfectedEncounterCreateInput,
) *models.InfectedEncounter {
	if m == nil {
		return nil
	}
	r := &models.InfectedEncounter{
		PossibleInfectedHash: m.PossibleInfectedHash,
		Rssi:                 m.Rssi,
		Hits:                 m.Hits,
		Time:                 m.Time,
		Duration:             m.Duration,
	}
	return r
}

func InfectedEncounterCreateInputToModelM(
	input map[string]interface{},
	m graphql_models.InfectedEncounterCreateInput,
) models.M {
	modelM := models.M{}
	for key, _ := range input {
		switch key {
		case "possibleInfectedHash":
			modelM[models.InfectedEncounterColumns.PossibleInfectedHash] = m.PossibleInfectedHash
		case "rssi":
			modelM[models.InfectedEncounterColumns.Rssi] = m.Rssi
		case "hits":
			modelM[models.InfectedEncounterColumns.Hits] = m.Hits
		case "time":
			modelM[models.InfectedEncounterColumns.Time] = m.Time
		case "duration":
			modelM[models.InfectedEncounterColumns.Duration] = m.Duration
		}
	}
	return modelM
}

func InfectedEncounterCreateInputToBoilerWhitelist(input map[string]interface{}, extraColumns ...string) boil.Columns {
	columnsWhichAreSet := []string{}
	for key, _ := range input {
		switch key {
		case "possibleInfectedHash":
			columnsWhichAreSet = append(columnsWhichAreSet, models.InfectedEncounterColumns.PossibleInfectedHash)
		case "rssi":
			columnsWhichAreSet = append(columnsWhichAreSet, models.InfectedEncounterColumns.Rssi)
		case "hits":
			columnsWhichAreSet = append(columnsWhichAreSet, models.InfectedEncounterColumns.Hits)
		case "time":
			columnsWhichAreSet = append(columnsWhichAreSet, models.InfectedEncounterColumns.Time)
		case "duration":
			columnsWhichAreSet = append(columnsWhichAreSet, models.InfectedEncounterColumns.Duration)
		}
	}
	columnsWhichAreSet = append(columnsWhichAreSet, extraColumns...)
	return boil.Whitelist(columnsWhichAreSet...)
}

func InfectionCreateKeyInputsToBoiler(am []*graphql_models.InfectionCreateKeyInput) []*models.InfectionCreateKey {
	ar := make([]*models.InfectionCreateKey, len(am))
	for i, m := range am {
		ar[i] = InfectionCreateKeyInputToBoiler(
			m,
		)
	}
	return ar
}

func InfectionCreateKeyInputToBoiler(
	m *graphql_models.InfectionCreateKeyInput,
) *models.InfectionCreateKey {
	if m == nil {
		return nil
	}
	r := &models.InfectionCreateKey{
		Key:      m.Key,
		Password: m.Password,
	}
	return r
}

func InfectionCreateKeyInputToModelM(
	input map[string]interface{},
	m graphql_models.InfectionCreateKeyInput,
) models.M {
	modelM := models.M{}
	for key, _ := range input {
		switch key {
		case "key":
			modelM[models.InfectionCreateKeyColumns.Key] = m.Key
		case "password":
			modelM[models.InfectionCreateKeyColumns.Password] = m.Password
		}
	}
	return modelM
}

func InfectionCreateKeyInputToBoilerWhitelist(input map[string]interface{}, extraColumns ...string) boil.Columns {
	columnsWhichAreSet := []string{}
	for key, _ := range input {
		switch key {
		case "key":
			columnsWhichAreSet = append(columnsWhichAreSet, models.InfectionCreateKeyColumns.Key)
		case "password":
			columnsWhichAreSet = append(columnsWhichAreSet, models.InfectionCreateKeyColumns.Password)
		}
	}
	columnsWhichAreSet = append(columnsWhichAreSet, extraColumns...)
	return boil.Whitelist(columnsWhichAreSet...)
}
