// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package helpers

import (
	"github.com/web-ridge/gqlgen-sqlboiler/helper"
)

var InfectionCreateKeyPreloadMap = map[string]helper.ColumnSetting{}
