// Code generated by SQLBoiler 3.6.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/queries/qm"
	"github.com/volatiletech/sqlboiler/queries/qmhelper"
	"github.com/volatiletech/sqlboiler/strmangle"
)

// InfectionCreateKey is an object representing the database table.
type InfectionCreateKey struct {
	ID       int    `boil:"id" json:"id" toml:"id" yaml:"id"`
	Key      string `boil:"key" json:"key" toml:"key" yaml:"key"`
	Password string `boil:"password" json:"password" toml:"password" yaml:"password"`
	Time     int    `boil:"time" json:"time" toml:"time" yaml:"time"`

	R *infectionCreateKeyR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L infectionCreateKeyL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var InfectionCreateKeyColumns = struct {
	ID       string
	Key      string
	Password string
	Time     string
}{
	ID:       "id",
	Key:      "key",
	Password: "password",
	Time:     "time",
}

// Generated where

var InfectionCreateKeyWhere = struct {
	ID       whereHelperint
	Key      whereHelperstring
	Password whereHelperstring
	Time     whereHelperint
}{
	ID:       whereHelperint{field: "\"infection_create_key\".\"id\""},
	Key:      whereHelperstring{field: "\"infection_create_key\".\"key\""},
	Password: whereHelperstring{field: "\"infection_create_key\".\"password\""},
	Time:     whereHelperint{field: "\"infection_create_key\".\"time\""},
}

// InfectionCreateKeyRels is where relationship names are stored.
var InfectionCreateKeyRels = struct {
}{}

// infectionCreateKeyR is where relationships are stored.
type infectionCreateKeyR struct {
}

// NewStruct creates a new relationship struct
func (*infectionCreateKeyR) NewStruct() *infectionCreateKeyR {
	return &infectionCreateKeyR{}
}

// infectionCreateKeyL is where Load methods for each relationship are stored.
type infectionCreateKeyL struct{}

var (
	infectionCreateKeyAllColumns            = []string{"id", "key", "password", "time"}
	infectionCreateKeyColumnsWithoutDefault = []string{"key", "password", "time"}
	infectionCreateKeyColumnsWithDefault    = []string{"id"}
	infectionCreateKeyPrimaryKeyColumns     = []string{"id"}
)

type (
	// InfectionCreateKeySlice is an alias for a slice of pointers to InfectionCreateKey.
	// This should generally be used opposed to []InfectionCreateKey.
	InfectionCreateKeySlice []*InfectionCreateKey
	// InfectionCreateKeyHook is the signature for custom InfectionCreateKey hook methods
	InfectionCreateKeyHook func(context.Context, boil.ContextExecutor, *InfectionCreateKey) error

	infectionCreateKeyQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	infectionCreateKeyType                 = reflect.TypeOf(&InfectionCreateKey{})
	infectionCreateKeyMapping              = queries.MakeStructMapping(infectionCreateKeyType)
	infectionCreateKeyPrimaryKeyMapping, _ = queries.BindMapping(infectionCreateKeyType, infectionCreateKeyMapping, infectionCreateKeyPrimaryKeyColumns)
	infectionCreateKeyInsertCacheMut       sync.RWMutex
	infectionCreateKeyInsertCache          = make(map[string]insertCache)
	infectionCreateKeyUpdateCacheMut       sync.RWMutex
	infectionCreateKeyUpdateCache          = make(map[string]updateCache)
	infectionCreateKeyUpsertCacheMut       sync.RWMutex
	infectionCreateKeyUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var infectionCreateKeyBeforeInsertHooks []InfectionCreateKeyHook
var infectionCreateKeyBeforeUpdateHooks []InfectionCreateKeyHook
var infectionCreateKeyBeforeDeleteHooks []InfectionCreateKeyHook
var infectionCreateKeyBeforeUpsertHooks []InfectionCreateKeyHook

var infectionCreateKeyAfterInsertHooks []InfectionCreateKeyHook
var infectionCreateKeyAfterSelectHooks []InfectionCreateKeyHook
var infectionCreateKeyAfterUpdateHooks []InfectionCreateKeyHook
var infectionCreateKeyAfterDeleteHooks []InfectionCreateKeyHook
var infectionCreateKeyAfterUpsertHooks []InfectionCreateKeyHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *InfectionCreateKey) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range infectionCreateKeyBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *InfectionCreateKey) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range infectionCreateKeyBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *InfectionCreateKey) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range infectionCreateKeyBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *InfectionCreateKey) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range infectionCreateKeyBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *InfectionCreateKey) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range infectionCreateKeyAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *InfectionCreateKey) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range infectionCreateKeyAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *InfectionCreateKey) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range infectionCreateKeyAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *InfectionCreateKey) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range infectionCreateKeyAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *InfectionCreateKey) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range infectionCreateKeyAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddInfectionCreateKeyHook registers your hook function for all future operations.
func AddInfectionCreateKeyHook(hookPoint boil.HookPoint, infectionCreateKeyHook InfectionCreateKeyHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		infectionCreateKeyBeforeInsertHooks = append(infectionCreateKeyBeforeInsertHooks, infectionCreateKeyHook)
	case boil.BeforeUpdateHook:
		infectionCreateKeyBeforeUpdateHooks = append(infectionCreateKeyBeforeUpdateHooks, infectionCreateKeyHook)
	case boil.BeforeDeleteHook:
		infectionCreateKeyBeforeDeleteHooks = append(infectionCreateKeyBeforeDeleteHooks, infectionCreateKeyHook)
	case boil.BeforeUpsertHook:
		infectionCreateKeyBeforeUpsertHooks = append(infectionCreateKeyBeforeUpsertHooks, infectionCreateKeyHook)
	case boil.AfterInsertHook:
		infectionCreateKeyAfterInsertHooks = append(infectionCreateKeyAfterInsertHooks, infectionCreateKeyHook)
	case boil.AfterSelectHook:
		infectionCreateKeyAfterSelectHooks = append(infectionCreateKeyAfterSelectHooks, infectionCreateKeyHook)
	case boil.AfterUpdateHook:
		infectionCreateKeyAfterUpdateHooks = append(infectionCreateKeyAfterUpdateHooks, infectionCreateKeyHook)
	case boil.AfterDeleteHook:
		infectionCreateKeyAfterDeleteHooks = append(infectionCreateKeyAfterDeleteHooks, infectionCreateKeyHook)
	case boil.AfterUpsertHook:
		infectionCreateKeyAfterUpsertHooks = append(infectionCreateKeyAfterUpsertHooks, infectionCreateKeyHook)
	}
}

// One returns a single infectionCreateKey record from the query.
func (q infectionCreateKeyQuery) One(ctx context.Context, exec boil.ContextExecutor) (*InfectionCreateKey, error) {
	o := &InfectionCreateKey{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for infection_create_key")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all InfectionCreateKey records from the query.
func (q infectionCreateKeyQuery) All(ctx context.Context, exec boil.ContextExecutor) (InfectionCreateKeySlice, error) {
	var o []*InfectionCreateKey

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to InfectionCreateKey slice")
	}

	if len(infectionCreateKeyAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all InfectionCreateKey records in the query.
func (q infectionCreateKeyQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count infection_create_key rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q infectionCreateKeyQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if infection_create_key exists")
	}

	return count > 0, nil
}

// InfectionCreateKeys retrieves all the records using an executor.
func InfectionCreateKeys(mods ...qm.QueryMod) infectionCreateKeyQuery {
	mods = append(mods, qm.From("\"infection_create_key\""))
	return infectionCreateKeyQuery{NewQuery(mods...)}
}

// FindInfectionCreateKey retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindInfectionCreateKey(ctx context.Context, exec boil.ContextExecutor, iD int, selectCols ...string) (*InfectionCreateKey, error) {
	infectionCreateKeyObj := &InfectionCreateKey{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"infection_create_key\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, infectionCreateKeyObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from infection_create_key")
	}

	return infectionCreateKeyObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *InfectionCreateKey) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no infection_create_key provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(infectionCreateKeyColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	infectionCreateKeyInsertCacheMut.RLock()
	cache, cached := infectionCreateKeyInsertCache[key]
	infectionCreateKeyInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			infectionCreateKeyAllColumns,
			infectionCreateKeyColumnsWithDefault,
			infectionCreateKeyColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(infectionCreateKeyType, infectionCreateKeyMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(infectionCreateKeyType, infectionCreateKeyMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"infection_create_key\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"infection_create_key\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into infection_create_key")
	}

	if !cached {
		infectionCreateKeyInsertCacheMut.Lock()
		infectionCreateKeyInsertCache[key] = cache
		infectionCreateKeyInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the InfectionCreateKey.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *InfectionCreateKey) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	infectionCreateKeyUpdateCacheMut.RLock()
	cache, cached := infectionCreateKeyUpdateCache[key]
	infectionCreateKeyUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			infectionCreateKeyAllColumns,
			infectionCreateKeyPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update infection_create_key, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"infection_create_key\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, infectionCreateKeyPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(infectionCreateKeyType, infectionCreateKeyMapping, append(wl, infectionCreateKeyPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update infection_create_key row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for infection_create_key")
	}

	if !cached {
		infectionCreateKeyUpdateCacheMut.Lock()
		infectionCreateKeyUpdateCache[key] = cache
		infectionCreateKeyUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q infectionCreateKeyQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for infection_create_key")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for infection_create_key")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o InfectionCreateKeySlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), infectionCreateKeyPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"infection_create_key\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, infectionCreateKeyPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in infectionCreateKey slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all infectionCreateKey")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *InfectionCreateKey) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no infection_create_key provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(infectionCreateKeyColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	infectionCreateKeyUpsertCacheMut.RLock()
	cache, cached := infectionCreateKeyUpsertCache[key]
	infectionCreateKeyUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			infectionCreateKeyAllColumns,
			infectionCreateKeyColumnsWithDefault,
			infectionCreateKeyColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			infectionCreateKeyAllColumns,
			infectionCreateKeyPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert infection_create_key, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(infectionCreateKeyPrimaryKeyColumns))
			copy(conflict, infectionCreateKeyPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"infection_create_key\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(infectionCreateKeyType, infectionCreateKeyMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(infectionCreateKeyType, infectionCreateKeyMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if err == sql.ErrNoRows {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert infection_create_key")
	}

	if !cached {
		infectionCreateKeyUpsertCacheMut.Lock()
		infectionCreateKeyUpsertCache[key] = cache
		infectionCreateKeyUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single InfectionCreateKey record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *InfectionCreateKey) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no InfectionCreateKey provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), infectionCreateKeyPrimaryKeyMapping)
	sql := "DELETE FROM \"infection_create_key\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from infection_create_key")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for infection_create_key")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q infectionCreateKeyQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no infectionCreateKeyQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from infection_create_key")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for infection_create_key")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o InfectionCreateKeySlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(infectionCreateKeyBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), infectionCreateKeyPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"infection_create_key\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, infectionCreateKeyPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from infectionCreateKey slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for infection_create_key")
	}

	if len(infectionCreateKeyAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *InfectionCreateKey) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindInfectionCreateKey(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *InfectionCreateKeySlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := InfectionCreateKeySlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), infectionCreateKeyPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"infection_create_key\".* FROM \"infection_create_key\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, infectionCreateKeyPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in InfectionCreateKeySlice")
	}

	*o = slice

	return nil
}

// InfectionCreateKeyExists checks if the InfectionCreateKey row exists.
func InfectionCreateKeyExists(ctx context.Context, exec boil.ContextExecutor, iD int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"infection_create_key\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if infection_create_key exists")
	}

	return exists, nil
}
